name: 'PR Merge Bot'
description: 'Merge pull requests when certain conditions are met'
branding:
  icon: 'git-merge'
  color: 'purple'
inputs:
  test:
    description: 'Runs in test mode and will comment rather than merge'
    required: false
    default: 'false'
  labels:
    description: 'Labels required for integration'
    required: true
    default: 'ready'
  blocking_labels:
    description: 'Labels that block the integration'
    required: false
    default: 'do not merge'
  reviewers:
    description: 'Reviewers required and reviewers must all approve'
    required: false
    default: 'true'
  checks_enabled:
    description: 'All checks must be completed to be eligible to integrate (except the current Action)'
    required: false
    default: 'false'
  method:
    description: 'Merge method to use. Possible values are `merge`, `squash` or `rebase`. Default is `merge`.'
    required: false
    default: 'merge'
  delete_source_branch:
    description: If true, delete the source branch of the pull request after merging
    required: false
    default: 'true'
  GITHUB_TOKEN:
    description: 'Authorization Token for accessing GitHub'
    required: false
  GITHUB_APP_ID:
    description: 'App Id for GitHub App'
    required: false
  GITHUB_APP_PRIVATE_KEY:
    description: 'App private key for GitHub App'
    required: false
  GITHUB_APP_CLIENT_ID:
    description: 'App client id for GitHub App'
    required: false
  GITHUB_APP_CLIENT_SECRET:
    description: 'App client secret for GitHub App'
    required: false
runs:
  using: 'node12'
  main: 'index.js'
